miaplicacion/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.base, name='base'),
   
    
    path('vendedor/',views.listar_vendedor,name='listar_vendedor'),
    path('vendedor/ver/<int:pk>/',views.ver_vendedor,name='ver_vendedor'),
    path('vendedor/crear',views.crear_vendedor,name='crear_vendedor'),
    path('vendedor/editar/<int:pk>/',views.editar_vendedor,name='editar_vendedor'),
    path('vendedor/eliminar/<int:pk>/',views.eliminar_vendedor,name='eliminar_vendedor'),
    
    path('cliente/',views.listar_cliente,name='listar_cliente'),
    path('cliente/crear/',views.crear_cliente,name='crear_cliente'),
    path('cliente/editar/<int:pk>/',views.editar_cliente,name='editar_cliente'),
    path('cliente/eliminar/<int:pk>/',views.eliminar_cliente,name='eliminar_cliente'),
    
    path('deportivo/',views.listar_deportivo,name='listar_deportivo'),
    path('deportivo/crear/',views.crear_deportivo,name='crear_deportivo'),
    path('deportivo/editar/<int:pk>/',views.editar_deportivo,name='editar_deportivo'),
    path('deportivo/eliminar/<int:pk>/',views.eliminar_deportivo,name='eliminar_deportivo'),
    
    
    path('compra/',views.listar_compra,name='listar_compra'),
    path('compra/crear/',views.crear_compra,name='crear_compra'),
    path('compra/editar/<int:pk>/',views.editar_compra,name='editar_compra'),
    path('compra/eliminar/<int:pk>/',views.eliminar_compra,name='eliminar_compra'),
    
    path('rol/',views.listar_roles,name='listar_rol'),
    path('rol/crear/',views.crear_rol,name='crear_rol'),
    path('rol/editar/<int:pk>/',views.editar_rol,name='editar_rol'),
    path('rol/eliminar/<int:pk>/',views.eliminar_rol,name='eliminar_rol'),
    
    path('usuario/',views.listar_usario,name='listar_usuario'),
    path('usuario/crear/',views.crear_usario,name='crear_usuario'),
    path('usuario/editar/<int:pk>/',views.editar_usuario,name='editar_usuario'),
    path('usuario/eliminar/<int:pk>/',views.eliminar_usuario,name='eliminar_usuario'),
    
    
    
    #Url Login y Logout
    path('accounts/login/',views.iniciar_sesion , name='login'),
    path('accounts/logot/',views.iniciar_sesion , name='logout'),
    
    
    #URL accesco denegado
    path('acceso_denegado/',views.acceso_denegado , name='acceso_denegado'),
    
   # URL Cambio de Contraseña
    path('cambiar_contraseña/', views.cambiar_contraseña, name='cambiar_contraseña'),
    
    
]+static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

miaplicacion/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Rol(models.Model):
    nombre=models.CharField(max_length=255,blank=False)

class Usuario(AbstractUser):
    createAt = models.DateField(auto_now_add = True)
    rol = models.ForeignKey(Rol, on_delete = models.CASCADE, null = False)
    email = models.EmailField(max_length = 255, blank = False, unique = True)

class Vendedor(models.Model):
    nombre=models.CharField(max_length=255,blank=False)
    apellidos=models.CharField(max_length=255,blank=False)
    anos_trabajo=models.IntegerField(null=False,blank=False)
    
class Cliente(models.Model):
    nombre = models.CharField(max_length = 255, blank = False)
    direccion = models.CharField(max_length = 255, blank = False)
    telefono = models.IntegerField(null = False, blank = False)
    vendedor = models.ForeignKey(Vendedor, on_delete = models.CASCADE)

class Deportivo(models.Model):
    modelo=models.CharField(max_length=155,blank=False)
    marca=models.CharField(max_length=155,blank=False)
    precio=models.FloatField(null=False)
    kilometraje=models.IntegerField(null=False,blank=False)
    caballos_fuerza=models.IntegerField(null=False,blank=False)
    imagen=models.ImageField(upload_to='imagenes/',default='imagen')
    
class Registro_Compra(models.Model):
    monto=models.FloatField(null=False)
    cliente=models.ForeignKey(Cliente,on_delete=models.CASCADE)
    deportivo=models.ForeignKey(Deportivo,on_delete=models.CASCADE)
    fechaC=models.DateField(auto_now_add=True)

miaplicacion/forms.py
from django import forms
from .models import Vendedor, Cliente, Deportivo, Registro_Compra, Rol, Usuario
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm

# Formulario Rol 
class RolForm(forms.ModelForm):
    class Meta:
        model = Rol
        fields = ['nombre']

# Formulario usuario
class UsuarioForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['username', 'first_name', 'last_name', 'email', 'rol', 'password1', 'password2']
        exclude = ['createAt']

#Formulario para edición basico de el usuario
class EditarUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'email', 'rol']
        exclude = ['createAt']

#Formulario Vendedor    
class VendedorForm(forms.ModelForm):
    class Meta:
        model = Vendedor
        fields = ['nombre','apellidos','anos_trabajo']

class ClienteForm(forms.ModelForm):
    vendedor = forms.ModelChoiceField(queryset = Vendedor.objects.all(), empty_label = "Seleccione un Vendedor")
    class Meta:
        model = Cliente
        fields = ['nombre','direccion', 'telefono','vendedor']
        

class DeportivoForm(forms.ModelForm):
    class Meta:
       model = Deportivo
       fields = ['modelo','marca','precio','kilometraje','caballos_fuerza','imagen']
       labels={
           'modelo':'Modelo',
           'marca':'Marca',
           'precio':'Precio',
           'kilometraje':'kilometraje',
           'caballos_fuerza':'Caballos de Fuerza',
           'imagen':'Imagen del Auto',
       }
       widgets={
           'modelo':forms.TextInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Modelo'
               }
           ),
           'marca':forms.TextInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Marca'
               }
           ),
           'precio':forms.NumberInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Precio'
               }
           ),
           'kilometraje':forms.NumberInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Kilometraje'
               }
           ),
           'caballos_fuerza':forms.NumberInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Caballos de Fuerza'
               }
           ),
           'imagen':forms.FileInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Imagen del Auto'
               }
           )
          
           
       }
    
class CompraForm(forms.ModelForm):
    class Meta:
       model = Registro_Compra
       fields = ['deportivo','cliente','monto']
       exclude = ['createAt']
    
    
            
               
       
   


# FORMULARIO de Cambio de Contraseña
class ClientePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        label = "Contraseña actual",
        widget = forms.PasswordInput(), 
        required = True
    )
    new_password1 = forms.CharField(
        label = "Nueva contraseña",
        widget = forms.PasswordInput(),
        required = True
    )
    new_password2 = forms.CharField(
        label = "Confirmar nueva contraseña",
        widget = forms.PasswordInput(),
        required = True
    )       

          

miaplicacion/templates/cliente/crear.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>

<head>
    {% block title %} <title>SIGFE-Crear Cliente</title> {% endblock %}
</head>

<body>

{% block contenido %}
<div class="main-panel">
  <div class="content">
    <div class="panel-header bg-primary-gradient">
      <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
          <div>
            <h1 class="text-white pb-2 fw-bold">
              SIGFE - Sistema Informático para la Gestión de Facturas Electrónicas
            </h1>
          </div>
        </div>
      </div>
    </div>
    <div class="page-inner mt-5">
      <div class="container">
        <div class="card shadow">
          <div class="card-header">
            <h4 class="card-title text-center">Formulario de Insercción de Datos del Cliente</h4>
          </div>
          <div class="card-body">
            {% if form.errors %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <strong>¡Error!</strong> Por favor corrija los siguientes errores:
              <ul>
                {% for field, errors in form.errors.items %}
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
                {% endfor %}
              </ul>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endif %}
            <div class="row">
              <div class="col-md-8 offset-md-2">
                <form method="post">
                  {% csrf_token %}

                  <!-- Campo: Nombre -->
                  <div class="form-group">
                    <label for="id_nombre">Nombre:</label>
                    <input id="id_nombre" type="text" class="form-control" name="nombre" required
                     placeholder="Nombre" >
                  </div>

                  <!-- Campo: Dirección -->
                  <div class="form-group">
                    <label for="id_direccion">Direccion:</label>
                    <input id="id_direccion" type="text" class="form-control" name="direccion" required
                     placeholder="Direccion" >
                  </div>

                  <!-- Campo: Telefóno del cliente -->
                  <div class="form-group">
                    <label for="id_telefono">Telefóno</label>
                    <input id="id_telefono" type="number" class="form-control" name="telefono" required
                     placeholder="Telefóno" >
                  </div>

                  <!-- Campo: Vendedor -->
                  <div class="form-group">
                    <label for="id_vendedor">Vendedor:</label>
                    <select id="id_vendedor" class="form-control" name="vendedor" required>
                      <option value="" selected disabled>Seleccione un Vendedor</option>
                      {% for vendedor in vendedor %}
                      <option value="{{ vendedor.id }}">{{ vendedor.nombre }}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="text-center">
                    <button type="submit" class="btn btn-success">Guardar Cliente</button>
                    <a href="{% url 'listar_cliente' %}" class="btn btn-danger ml-2">Volver al Listado de Clientes</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% block footer %} {{ block.super }} {% endblock %}
</div>
{% endblock %}
</body>

</html>

miaplicacion/templates/cliente/editar.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>

<head>
    {% block title %} <title>SIGFE- Editar Datos del Cliente</title> {% endblock %}
</head>

<body>

{% block contenido %}
<div class="main-panel">
    <div class="content">
        <div class="panel-header bg-primary-gradient">
            <div class="page-inner py-5">
                <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                    <div>
                        <h1 class="text-white pb-2 fw-bold">
                            Audi - Sistema Informático para la Gestión de Ventas Automoviles
                        </h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-inner mt-5">
            <div class="container">
                <div class="card shadow">
                    <div class="card-header">
                        <h4 class="card-title text-center">Formulario de Edición de Datos Básicos del Cliente</h4>
                    </div>
                    <div class="card-body">
                        {% if form.errors %}
                                    <div class="alert alert-danger">
                                        <strong>Error:</strong> Por favor corrija los siguientes errores.
                                        <ul>
                                            {% for field, errors in form.errors.items %}
                                                {% for error in errors %}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                    <li>{{ error }}</li>                                                    
                                                {% endfor %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                        {% endif %}
                        <div class="row">
                            <div class="col-md-8 offset-md-2">
                                <form method="post">
                                    {% csrf_token %}
                                     <!-- Campo: Nombre -->
                                    <div class="form-group">
                                        <label for="id_nombre">Nombre:</label>
                                        <input id="id_nombre" type="text" class="form-control" name="nombre" required
                                        placeholder="Nombre" value="{{form_cliente.nombre.value}}">
                                    </div>

                                    <!-- Campo: Dirección -->
                                    <div class="form-group">
                                        <label for="id_direccion">Direccion:</label>
                                        <input id="id_direccion" type="text" class="form-control" name="direccion" required
                                        placeholder="Direccion" value="{{form_cliente.direccion.value}}">
                                    </div>

                                    <!-- Campo: Telefóno del cliente -->
                                    <div class="form-group">
                                        <label for="id_telefono">Telefóno</label>
                                        <input id="id_telefono" type="number" class="form-control" name="telefono" required
                                        placeholder="Telefóno" value="{{ form_cliente.telefono.value }}">
                                    </div>

                                    <!-- Campo: Vendedor -->
                                    <div class="form-group">
                                        <label for="id_vendedor">Vendedor:</label>  
                                        <select id="id_vendedor" class="form-control" name="vendedor" required>
                                            <option value="id_vendedor" selected disabled>Seleccione el Vendedor</option>
                                            {% for vendedor in form_cliente.fields.vendedor.queryset %}
                                                    <option value="{{ vendedor.id }}" {% if vendedor.id == form_cliente.instance.vendedor.id %} selected {% endif %}>{{ vendedor.nombre }} {{ vendedor.apellidos }} </option>
                                            {% endfor %}
                                          </select>
                                    </div>

                                    <div class="form-group text-center">
                                        <button type="submit" class="btn btn-primary">Guardar</button>
                                        <a href="{% url 'listar_cliente' %}" class="btn btn-warning ml-2">Regresar</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block footer %} {{ block.super }} {% endblock %}
</div>
{% endblock %}
</body>

</html>

miaplicacion/templates/cliente/eliminar.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    {% block title %} <title>Eliminar Cliente</title> {% endblock %}
</head>

<body>
    {% block contenido %}
        <h1>Eliminar Cliente</h1>

        <p>¿Estás seguro de que deseas eliminar al cliente "{{ cliente.nombre }}"?</p>

        <form action="{% url 'eliminar_cliente' cliente.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Confirmar Eliminar</button>
        </form>

        <a href="{% url 'listar_cliente' %}">Cancelar y Volver al Listado de Clientes</a>
    {% endblock %}
</body>
</html>

miaplicacion/templates/cliente/listar.html
1{% extends 'base.html' %}
<!DOCTYPE html>
<html>

<head>
    {% block title %} <title>SIGFE-Listado de Clientes</title> {% endblock %}
</head>

<body>
    {% block contenido %}
    <div class="main-panel">
        <div class="content">
            <div class="panel-header bg-primary-gradient">
                <div class="page-inner py-5">
                    <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                        <div>
                            <h1 class="text-white pb-2 fw-bold">SIGFE - Sistema Informático para la Gestión de Facturas
                                Electrónicas</h1>
                        </div>
                    </div>
                </div>
            </div>
            <div class="page-inner mt--5">
                <div class="col-md-12">
                    {% if messages %}
                    <div class="alert alert-success" id="alert-success">
                        <ul class="lista-mensajes">
                            {% for message in messages %}
                                <li  {% if message.tags %}  {% endif %}>{{message}}</li>
                            {%endfor%}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </ul>   
                    </div>
                    {% endif %}
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex align-items-center">
                                <h4 class="card-title">Listado de Clientes</h4>
                                {% if user.rol.nombre == 'Administrador' %}
                                <form action="{% url 'crear_cliente' %}" method="get" class="btn ml-auto">
                                    <button class="btn btn-primary btn-round ml-auto">
                                        <i class="fa fa-plus"></i>&nbsp;Insertar Cliente
                                    </button>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="add-row" class="display table table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Dirección</th>
                                            <th>Telefono</th>
                                            <th>Vendedor</th>
                                            {% if user.rol.nombre == 'Administrador' %}
                                            <th style="width: 10%">Acción</th>
                                            {% endif %}
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Dirección</th>
                                            <th>Telefono</th>
                                            <th>Vendedor</th>
                                            
                                            {% if user.rol.nombre == 'Administrador' %}
                                            <th>Acción</th>
                                            {% endif%}
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for cliente in cliente %}
                                        <tr>
                                            <td>{{ cliente.nombre }}</td>
                                            <td>{{ cliente.direccion }}</td>
                                            <td>{{ cliente.telefono }}</td>
                                            <td>{{ cliente.vendedor.nombre }} {{ cliente.vendedor.apellidos}}</td>
                                            {% if user.rol.nombre == 'Administrador' %}
                                            <td>
                                                <div class="form-button-action">
                                                    <a type="button" href="{% url 'editar_cliente' cliente.id %}"
                                                        class="btn btn-link btn-primary btn-lg">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    <button type="button" data-toggle="modal" title=""
                                                        class="btn btn-link btn-danger"
                                                        data-target="#eliminarModal{{ cliente.id }}">
                                                        <i class="fa fa-times"></i>
                                                    </button>
                                                    <!-- Modal de Confirmación de Eliminación -->
                                                    <div class="modal fade" id="eliminarModal{{ cliente.id }}"
                                                        tabindex="-1" role="dialog"
                                                        aria-labelledby="eliminarModalLabel{{ cliente.id }}"
                                                        aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title"
                                                                        id="eliminarModalLabel{{ cliente.id }}">
                                                                        Confirmar Eliminación</h5>
                                                                    <button type="button" class="close"
                                                                        data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    ¿Estás seguro que deseas eliminar el cliente
                                                                    <strong>{{ cliente.nombre }} </strong>?
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary"
                                                                        data-dismiss="modal">Cancelar</button>
                                                                    <form
                                                                        action="{% url 'eliminar_cliente' cliente.id %}"
                                                                        method="post">
                                                                        {% csrf_token %}
                                                                        <input type="submit" class="btn btn-danger"
                                                                            value="Eliminar">
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% block footer %} {{ block.super }} {% endblock %}
    </div>
    {% endblock %}
    {% block javascript %} {{ block.super }} {% endblock %}
</body>

</html>