miaplicacion/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.base, name='base'),
   
    
    path('vendedor/',views.listar_vendedor,name='listar_vendedor'),
    path('vendedor/ver/<int:pk>/',views.ver_vendedor,name='ver_vendedor'),
    path('vendedor/crear',views.crear_vendedor,name='crear_vendedor'),
    path('vendedor/editar/<int:pk>/',views.editar_vendedor,name='editar_vendedor'),
    path('vendedor/eliminar/<int:pk>/',views.eliminar_vendedor,name='eliminar_vendedor'),
    
    path('cliente/',views.listar_cliente,name='listar_cliente'),
    path('cliente/crear/',views.crear_cliente,name='crear_cliente'),
    path('cliente/editar/<int:pk>/',views.editar_cliente,name='editar_cliente'),
    path('cliente/eliminar/<int:pk>/',views.eliminar_cliente,name='eliminar_cliente'),
    
    path('deportivo/',views.listar_deportivo,name='listar_deportivo'),
    path('deportivo/crear/',views.crear_deportivo,name='crear_deportivo'),
    path('deportivo/editar/<int:pk>/',views.editar_deportivo,name='editar_deportivo'),
    path('deportivo/eliminar/<int:pk>/',views.eliminar_deportivo,name='eliminar_deportivo'),
    
    
    path('compra/',views.listar_compra,name='listar_compra'),
    path('compra/crear/',views.crear_compra,name='crear_compra'),
    path('compra/editar/<int:pk>/',views.editar_compra,name='editar_compra'),
    path('compra/eliminar/<int:pk>/',views.eliminar_compra,name='eliminar_compra'),
    
    path('rol/',views.listar_roles,name='listar_rol'),
    path('rol/crear/',views.crear_rol,name='crear_rol'),
    path('rol/editar/<int:pk>/',views.editar_rol,name='editar_rol'),
    path('rol/eliminar/<int:pk>/',views.eliminar_rol,name='eliminar_rol'),
    
    path('usuario/',views.listar_usario,name='listar_usuario'),
    path('usuario/crear/',views.crear_usario,name='crear_usuario'),
    path('usuario/editar/<int:pk>/',views.editar_usuario,name='editar_usuario'),
    path('usuario/eliminar/<int:pk>/',views.eliminar_usuario,name='eliminar_usuario'),
    
    
    
    #Url Login y Logout
    path('accounts/login/',views.iniciar_sesion , name='login'),
    path('accounts/logot/',views.iniciar_sesion , name='logout'),
    
    
    #URL accesco denegado
    path('acceso_denegado/',views.acceso_denegado , name='acceso_denegado'),
    
   # URL Cambio de Contraseña
    path('cambiar_contraseña/', views.cambiar_contraseña, name='cambiar_contraseña'),
    
    
]+static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

miaplicacion/forms.py
from django import forms
from .models import Vendedor, Cliente, Deportivo, Registro_Compra, Rol, Usuario
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm

# Formulario Rol 
class RolForm(forms.ModelForm):
    class Meta:
        model = Rol
        fields = ['nombre']

# Formulario usuario
class UsuarioForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['username', 'first_name', 'last_name', 'email', 'rol', 'password1', 'password2']
        exclude = ['createAt']

#Formulario para edición basico de el usuario
class EditarUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'email', 'rol']
        exclude = ['createAt']

#Formulario Vendedor    
class VendedorForm(forms.ModelForm):
    class Meta:
        model = Vendedor
        fields = ['nombre','apellidos','anos_trabajo']

class ClienteForm(forms.ModelForm):
    vendedor = forms.ModelChoiceField(queryset = Vendedor.objects.all(), empty_label = "Seleccione un Vendedor")
    class Meta:
        model = Cliente
        fields = ['nombre','direccion', 'telefono','vendedor']
        

class DeportivoForm(forms.ModelForm):
    class Meta:
       model = Deportivo
       fields = ['modelo','marca','precio','kilometraje','caballos_fuerza','imagen']
       labels={
           'modelo':'Modelo',
           'marca':'Marca',
           'precio':'Precio',
           'kilometraje':'kilometraje',
           'caballos_fuerza':'Caballos de Fuerza',
           'imagen':'Imagen del Auto',
       }
       widgets={
           'modelo':forms.TextInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Modelo'
               }
           ),
           'marca':forms.TextInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Marca'
               }
           ),
           'precio':forms.NumberInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Precio'
               }
           ),
           'kilometraje':forms.NumberInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Kilometraje'
               }
           ),
           'caballos_fuerza':forms.NumberInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Caballos de Fuerza'
               }
           ),
           'imagen':forms.FileInput(
               attrs={
                   'class':'form-control',
                   'placeholder':'Imagen del Auto'
               }
           )
          
           
       }
    
class CompraForm(forms.ModelForm):
    class Meta:
       model = Registro_Compra
       fields = ['deportivo','cliente','monto']
       exclude = ['createAt']
    
    
            
               
       
   


# FORMULARIO de Cambio de Contraseña
class ClientePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        label = "Contraseña actual",
        widget = forms.PasswordInput(), 
        required = True
    )
    new_password1 = forms.CharField(
        label = "Nueva contraseña",
        widget = forms.PasswordInput(),
        required = True
    )
    new_password2 = forms.CharField(
        label = "Confirmar nueva contraseña",
        widget = forms.PasswordInput(),
        required = True
    )       

          

miaplicacion/templates/acceso_denegado.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>SIGFE - Acceso Denegado</title>

    <!-- Fonts and icons -->
    <script src="{% static 'assets/js/plugin/webfont/webfont.min.js' %}"></script>
    <script>
        WebFont.load({
            google: {"families":["Lato:300,400,700,900"]},
            custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ["{% static '/assets/css/fonts.min.css' %}"]},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>
    
    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/atlantis.min.css' %}">

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}">

    <style>
        body {
            background: linear-gradient(135deg, #007bff, #56ccf2);
            background-size: cover;
            background-repeat: no-repeat;
            height: 100vh;
            display: flex;
            justify-content: center; /* Centra horizontalmente */
            align-items: center; /* Centra verticalmente */
            overflow: hidden;
            position: relative;
            font-family: 'Lato', sans-serif;
        }
        .wrapper{
            display:flex;
            justify-content:center;
            align-items:center;
            flex-direction: column;
        }

        .access-denied-card {
            background-color: rgba(255, 255, 255, 0.9);
            border-radius: 10px;
            box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.2);
            padding: 30px;
            margin-top: 50px;
            width: 400px;
            max-width: 90%;
            text-align: center;
            transition: transform 0.5s ease; /* Animación de transformación */
            transform: translateY(-50px); /* Inicialmente trasladado hacia arriba */
            opacity: 0; /* Inicialmente oculto */
        }

        .access-denied-card.show {
            transform: translateY(0); /* Mostrar en el centro */
            opacity: 1; /* Hacer visible */
        }

        .access-denied-card h2 {
            font-size: 28px;
            margin-bottom: 30px;
            color: #333333;
            font-weight: bold;
        }

        .access-denied-card p {
            font-size: 16px;
            color: #555555;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="access-denied-card">
            <h2>Acceso Denegado</h2>
            <p>Estimado usuario, usted no tiene permiso suficiente para acceder al recurso solicitado.</p>
            <p>Por favor, contacte al administrador del sistema para obtener acceso.</p>
            <a href="{% url 'base' %}" class="btn btn-default">Regresar al Inicio</a>
        </div>
    </div>

    <!-- JS Files -->
    <script src="{% static 'assets/js/core/jquery.3.2.1.min.js' %}"></script>
    <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>

    
    <script>
        $(document).ready(function() {
            $('.access-denied-card').addClass('show'); 
        });
    </script>
</body>
</html>

miaplicacion/templates/cambiar_contraseña.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Cambiar Contraseña</title>{% endblock %}

{% block contenido %}
<div class="main-panel">
    <div class="content">
        <div class="panel-header bg-primary-gradient">
            <div class="page-inner py-5">
                <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                    <div>
                        <h1 class="text-white pb-2 fw-bold">
                            SIGFE - Sistema Informático para la Gestión de Ventas de Automoviles
                        </h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-inner mt--5">
            <div class="col-md-12 text-center">
                {% if form.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>¡Error!</strong> Por favor corrija los siguientes errores:
                    <ul>
                        {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                        {% endfor %}
                    </ul>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div class="mx-auto" style="max-width: 500px;">
                    <div class="card-header text-center">
                        <!-- Imagen de Cabecera -->
                        <img src="{% static 'assets/img/9710382.png' %}" alt="Logo" class="img-fluid mb-4"
                            style="max-width: 50px;">
                        <h4 class="card-title">Cambiar Contraseña</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{% url 'cambiar_contraseña' %}">
                            {% csrf_token %}

                            <!-- Campo: Contraseña Actual -->
                            <div class="form-group">
                                <label for="id_old_password">Contraseña actual:</label>
                                <input id="id_old_password" type="password" name="old_password" class="form-control"
                                    required>
                            </div>

                            <!-- Campo: Nueva Contraseña -->
                            <div class="form-group">
                                <label for="id_new_password1">Nueva contraseña:</label>
                                <input id="id_new_password1" type="password" name="new_password1" class="form-control"
                                    required>
                            </div>

                            <!-- Campo: Confirmar Nueva Contraseña -->
                            <div class="form-group">
                                <label for="id_new_password2">Confirmar nueva contraseña:</label>
                                <input id="id_new_password2" type="password" name="new_password2" class="form-control"
                                    required>
                            </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-success">Cambiar Contraseña</button>
                                <a href="{% url 'base' %}" class="btn btn-secondary ml-2">Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block footer %} {{ block.super }} {% endblock %}
</div>
{% endblock %}

{% block javascript %} {{ block.super }} {% endblock %}

miaplicacion/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Iniciar Sesión - SIGFE</title>

    <!-- Fonts and icons -->
    <script src="{% static 'assets/js/plugin/webfont/webfont.min.js' %}"></script>
    <script>
        WebFont.load({
            google: {"families":["Lato:300,400,700,900"]},
            custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ["{% static '/assets/css/fonts.min.css' %}"]},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>
    
    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/atlantis.min.css' %}">

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}">

    <style>
        *{
            text-decoration: none;
            list-style: none;
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }
        body {
            background: linear-gradient(135deg, #007bff, #56ccf2);
            background-size: cover;
            background-repeat: no-repeat;
            width:100%;
            height: 100vh;
            display: flex;
            justify-content: center; /* Centra horizontalmente */
            align-items: center; /* Centra verticalmente */
            overflow: hidden;
            position: relative;
            font-family: 'Lato', sans-serif;
        }
        .wrapper{
            display:flex;
            justify-content:center;
            flex-direction: column;
            align-items:center;
        }

        .login-form {
            background-color:#09f ;
            border-radius: 10px;
            box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.2);
            padding: 30px;
            margin-top: 50px;
            width: 400px;
           
            max-width: 90%;
            text-align: center;
            transition: transform 0.5s ease; /* Animación de transformación */
            transform: translateY(-50px); /* Inicialmente trasladado hacia arriba */
            opacity: 0; /* Inicialmente oculto */
        }

        .login-form.show {
            transform: translateY(0); /* Mostrar en el centro */
            opacity: 1; /* Hacer visible */
        }

        .login-form h2 {
            font-size: 28px;
            margin-bottom: 30px;
            color: #fff;
            font-weight: bold;
        }

        .login-form input[type="text"], 
        .login-form input[type="password"] {
            width: calc(100% - 40px);
            padding: 12px;
            margin-bottom: 20px;
            border: 1px solid #e3e3e3;
            border-radius: 5px;
            font-size: 16px;
            transition: all 0.3s ease;
            background:transparent;
            color:#fff;
        }

        .login-form input[type="text"]:focus, 
        .login-form input[type="password"]:focus {
            outline: none;
            border-color: #007ced;
            box-shadow: 0 0 10px rgba(0, 123, 255, 0.4);
        }
        
       

        .login-form button {
            width: 100%;
            padding: 14px;
            border: none;
            border-radius: 5px;
            background-color: #007ff4;
            color: #ffffff;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .login-form button:hover {
            background-color:#007ced;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="login-form" clase="show">
            <img src="{% static 'assets/img/software-para-restaurantes-1.png' %}" alt="Logo" style="width: 80px; margin-bottom: 20px;">
            <h2>Iniciar Sesión</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Entrar</button>
            </form>
        </div>
    </div>

    <!-- JS Files -->
    <script src="{% static 'assets/js/core/jquery.3.2.1.min.js' %}"></script>
    <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>

    <!-- Script para mostrar la tarjeta de inicio de sesión de manera animada -->
    <script>
        $(document).ready(function() {
            $('.login-form').addClass('show'); // Agregar la clase show para mostrar animadamente la tarjeta
        });
    </script>
</body>
</html>